# permissions for end users to view algocodings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: algocoding-viewer-role
rules:
- apiGroups:
  - cache.algo.com
  resources:
  - algocodings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.algo.com
  resources:
  - algocodings/status
  verbs:
  - get
