# permissions for end users to view redisdbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisdb-viewer-role
rules:
- apiGroups:
  - cache.algo.com
  resources:
  - redisdbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.algo.com
  resources:
  - redisdbs/status
  verbs:
  - get
