apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: algo-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: AlgoCoding is the Schema for the algocodings API
      displayName: Algo Coding
      kind: AlgoCoding
      name: algocodings.cache.algo.com
      version: v1alpha1
  description: Algo Coding Operator for coder
  displayName: Algocoding operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - coding
  - algo
  - leetcode
  links:
  - name: Algo Operator
    url: https://algo-operator.domain
  maturity: alpha
  provider:
    name: Marco Y.
    url: www.leetcode.com/...
  version: 0.0.0
