apiVersion: cache.algo.com/v1alpha1
kind: AlgoCoding
metadata:
  name: algocoding-sample
spec:
  # Add fields here
  replicas: 2
  dbImage: quay.io/bclaster/roar-db:1.0.2
  webImage: quay.io/bclaster/roar-web:1.0.1
